<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>예외처리</title>
</head>
<body>
    
</body>
<script>
    try {
        const array = new Array(999999999999999)
    } catch (exception) {
        console.log(exception)
        console.log()
        console.log(`예외 이름: ${exception.name}`)
        console.log(`예외 메시지: ${exception.message}`)
    }
</script>

<!--예외 강제로 발생시키고 잡기-->

<script>
    function divide(a, b) {
        if (b === 0) {
            throw '0으로는 나눌 수 없습니다.'
        }
        return a / b
    }

    console.log(divide(10, 2))
    console.log(divide(10, 0))
</script>

<!--예외를 강제로 발생시키기-->
<script>
    function test(object) {
        console.log(object.a + object.b)
    }

    test({})
</script>

<!--예외를 강제로 발생시켜서 사용 유도하기-->
<script>
    function test(object) {
        if (object.a !== undefined && object.b !== undefined) {
            console.log(object.a + object.b)
        } else {
            throw new Error("a 속성과 b 속성을 지정하지 않았습니다.")
        }
    }

    test({})
</script>

<!--예제 8-2-3-->
<script>
    try {
        console.log('try 구문입니다.')
        const array = ['사과', '바나나', '귤']
        array.forEach(() => {
            throw '예외를 강제로 발생시킵니다.'
        })
    } catch (e) {
        console.log('catch 구문입니다.')
    } finally {
        console.log('finally 구문입니다.')
    }
</script>
</html>